# Generated by Django 5.2.16 on 2026-07-08 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=128)),
                ('company_size', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('new', 'New'), ('working', 'Working'), ('qualified', 'Qualified'), ('opportunity', 'Opportunity'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=128)),
                ('channel', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('intent_bucket', models.CharField(max_length=16)),
                ('explanation', models.TextField(blank=True)),
                ('model_name', models.CharField(max_length=64)),
                ('model_version', models.CharField(max_length=64)),
                ('feature_snapshot', models.JSONField(blank=True, default=dict)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('best_contact_window_start', models.DateTimeField(blank=True, null=True)),
                ('best_contact_window_end', models.DateTimeField(blank=True, null=True)),
                ('preferred_channel', models.CharField(max_length=32)),
                ('recommendation_type', models.CharField(max_length=64)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='leads.lead')),
                ('source_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='leads.prediction')),
            ],
        ),
    ]
